services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=challenge_chat'
      - 'POSTGRES_PASSWORD=challenge_chat'
      - 'POSTGRES_USER=challenge_chat'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
